{{- if and (not .Values.auth.existingSecret) .Values.auth.passphrase }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radicle-seed.authSecretName" . }}
  labels:
    {{- include "radicle-seed.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretKey }}: {{ .Values.auth.passphrase | quote }}
{{- end }}
