apiVersion: v2
name: radicle-seed
description: A hardened, persistent Radicle seed node with an optional read-only HTTP daemon
type: application
version: 0.1.1
appVersion: "1.9.1"
kubeVersion: ">=1.25.0-0"
home: https://radicle.dev/
icon: https://radicle.dev/assets/images/radicle.svg
sources:
  - https://github.com/radicle-dev/heartwood
  - https://github.com/radicle-dev/radicle-explorer
maintainers:
  - name: Tyler Schmidtke
keywords:
  - radicle
  - git
  - peer-to-peer
  - seed
annotations:
  artifacthub.io/category: developer-tools
  artifacthub.io/license: MIT
